# 关于博联万能遥控学习射频码的方式，iOS用户可以参考我写的另一个小工具。
# https://github.com/Erimus-Koo/Extract_BroadLink_learned_codes_from_iOS_App
# 非iOS用户，可以参考下官方文档。
# https://www.home-assistant.io/integrations/broadlink/
# 我在这里控制了大部分的传统家电和开关。
- platform: broadlink
  host: 10.0.0.30
  mac: !secret broadlink_mac
  timeout: 15
  switches:
    # amplifier ==============================
    amplifier_power:
      friendly_name: Amplifier Power
      command_on: JgBYAAABKpIVERQ1FTUVNhU1FTUVNRURFDUVERQSFBEUERQRFBIUNhQRFDYUERQ2FBIUNRURFBEUNRUSEzYVERQ2FBEUNRU1FQAFHgABKkgVAAxeAAEqSBUADQU=
      command_off: JgBYAAABKpIVERQ1FTUVNhU1FTUVNRURFDUVERQSFBEUERQRFBIUNhQRFDYUERQ2FBIUNRURFBEUNRUSEzYVERQ2FBEUNRU1FQAFHgABKkgVAAxeAAEqSBUADQU=
      # 这类遥控器虽然开关是同一个键，但还是要写on和off。
      # 简化方案是可以把off写成''，但在调用的时候，也只能对应用switch.trun_on。
      # 但是如果投射到homekit，它会区分开关状态并调用trunoff，所以只能复制一遍。

    amplifier_mute:
      friendly_name: Amplifier Mute
      command_on: JgBQAAABJ5QSEhI3EhISNxI3EjcSNxISEjcSEhI3EhISEhISEhISNxISEhISNxI3EjcSEhISEhISNxI3EhISEhISEjcSNxI3EgAFJQABJ0oSAAxS
      command_off: JgBQAAABJ5QSEhI3EhISNxI3EjcSNxISEjcSEhI3EhISEhISEhISNxISEhISNxI3EjcSEhISEhISNxI3EhISEhISEjcSNxI3EgAFJQABJ0oSAAxS

    amplifier_volume_up:
      friendly_name: Amplifier Vol +
      command_on: JgBQAAABJ5QSEhI3EhISNxI3EjcSNxISEjcSEhI3EhISEhISEhISNxISEjcSEhI3EjcSEhISEhISNxISEjcSEhISEjcSNxI3EgAFJQABJ0oSAAxS
      command_off: ''

    amplifier_volume_down:
      friendly_name: Amplifier Vol -
      command_on: JgBQAAABJ5QSEhI3EhISNxI3EjcSNxISEjcSEhI3EhISEhISEhISNxI3EjcSEhI3EjcSEhISEhISEhISEjcSEhISEjcSNxI3EgAFJQABJ0oSAAxS
      command_off: ''

    # projector ==============================
    projector_power:
      friendly_name: Projector
      command_on: JgBUAAABFocUEBIQExASEBMxFDETMxIyE4gTMhMQExASEBMQEhATMRQQEgADtQABFYgTEBIREhATEBIyEzEUMRQxE4gUMhIREhASERIQExASMhMQEwANBQAAAAA=
      command_off: JgBUAAABFYgTDxQPEw8UDxMyEzITMRQxFIcUDxMyEw8UDxMQEw8TMhMPFAADtAABFYgTEBMPExASEBQxEzITMhMyE4gTDxQxExATDxQPEw8UMRMQEwANBQAAAAA=

    # air conditioner ==============================
    # aircon_heat_30:
    #   friendly_name: Aircon Heating 30℃
    #   command_on: JgAWAnI2DycPDQ8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDycPDQ8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDycPDQ8nDycPJw8nDycPJw8NDycPJw8nDycPJw8nDycPJw8nDw0PDQ8NDw0PDQ8NDw0PDQ8NDw0PJw8nDw0PDQ8nDycPJw8nDw0PDQ8nDycPDQ8NDw0PJw8NDw0PJw8NDw0PJw8nDw0PJw8nDw0PJw8nDw0PJw8nDw0PDQ8nDw0PDQ8NDw0PDQ8nDycPDQ8nDycPJw8NDw0PDQ8nDycPJw8nDw0PJw8nDycPDQ8NDw0PDQ8nDw0PDQ8NDw0PDQ8NDw0PDQ8nDycPJw8nDycPJw8nDycPDQ8NDw0PDQ8NDw0PDQ8NDycPJw8nDycPJw8nDycPJw8NDw0PDQ8NDw0PDQ8NDw0PJw8nDycPJw8nDycPJw8nDw0PDQ8NDw0PDQ8NDw0PDQ8nDycPJw8nDycPJw8nDycPDQ8NDw0PDQ8NDw0PDQ8NDycPJw8nDycPJw8nDycPJw8NDycPJw8NDycPDQ8nDw0PJw8NDw0PJw8NDycPDQ8nDycPDQ8NDw0PJw8NDycPJw8NDycPJw8nDw0PJw8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDycPJw8nDycPJw8nDycPJw8NDw0PDQ8NDw0PDQ8NDw0PJw8nDycPJw8nDycPJw8nEgABSA==
    #   command_off: ''

    # aircon_cool_28:
    #   friendly_name: Aircon Cooling 28℃
    #   command_on: JgAWAnI2DycPDQ8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDycPDQ8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDycPDQ8nDycPJw8nDycPJw8NDycPJw8nDycPJw8nDycPJw8nDw0PDQ8NDw0PDQ8NDw0PDQ8NDw0PJw8nDw0PDQ8nDycPJw8nDw0PDQ8nDycPDQ8NDw0PJw8NDw0PJw8NDw0PJw8nDw0PJw8nDw0PJw8nDw0PJw8nDw0PDQ8nDw0PDQ8NDw0PDQ8nDycPDQ8nDycPJw8NDw0PDQ8NDycPJw8nDw0PJw8nDycPJw8NDw0PDQ8nDw0PDQ8NDw0PDQ8NDw0PDQ8nDycPJw8nDycPJw8nDycPDQ8NDw0PDQ8NDw0PDQ8NDycPJw8nDycPJw8nDycPJw8NDw0PDQ8NDw0PDQ8NDw0PJw8nDycPJw8nDycPJw8nDw0PDQ8NDw0PDQ8NDw0PDQ8nDycPJw8nDycPJw8nDycPDQ8NDw0PDQ8NDw0PDQ8NDycPJw8nDycPJw8nDycPJw8nDycPDQ8NDycPDQ8nDw0PDQ8NDycPJw8NDycPDQ8nDycPDQ8NDw0PJw8NDycPJw8NDycPJw8nDw0PJw8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDycPJw8nDycPJw8nDycPJw8NDw0PDQ8NDw0PDQ8NDw0PJw8nDycPJw8nDycPJw8nEgABSA==
    #   command_off: ''

    # aircon_fan_3:  # 3档送风
    #   friendly_name: Aircon Fan 3
    #   command_on: JgAWAnE2DygQDBAMDwwQDBAMEAwPDBAMEAwQDA8MECgQDA8MEAwQDBAMDwwQDBAMEAwPDBAMEAwQDA8MEAwQDBALECgQDBAnECgPKBAoDygQKA8MECgQJxAoECcQKBAnECgQJxAoEAsQDBAMEAwQCxAMEAwQDBALEAwQKA8oEAwQDA8oECgPKBAoDwwQDBAoDygQDBAMDwwQKBAMDwwQKBALEAwQKBAnEAwQJxAoEAwPKBAoDwwQKBAnEAwQDBAnEAwQDBAMDwwQDBAnECgQDBAnECgQJxAMEAwPDBAMECgPKBAoDwwQKBAnECgQJxAMEAwQDA8oEAwQDA8MEAwQDBAMDwwQDBAnECgQJxAoECcQKBAnECgQDA8MEAwQDBAMDwwQDBAMECcQKBAnECgQJxAoECcQKA8MEAwQDBAMDwwQDBANDwwPKBAoDygQKA8oECgPKBAoDwwQDBAMEAwPDBAMEAwQDA8oECcQKBAnECgQJxAoECcQDBAMEAwPDQ8MEAwQDA8MECgQJxAoECcQKBAnECgPKBAoDwwQDBANDwwPDBApDwwPDBAoECcQKBAnECgQDA8oECcQDBAMEAwQJxAMECcQKBAMDygQKA8oEAwQJxAMEA0PDQ4MEAwQDBAMDw0PDBAMECcQKBAnECgQJxAoECcQKBAMDw0PDQ8NDgwQDBAMEAwPKBAoDygQKA8oECgPKBAoDwANBQAA
    #   command_off: ''

    # aircon_power_off:
    #   friendly_name: Aircon Power OFF
    #   command_on: ''
    #   command_off: JgAWAnI2DycPDQ8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDycPDQ8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDycPDQ8nDycPJw8nDycPJw8NDycPJw8nDycPJw8nDycPJw8nDw0PDQ8NDw0PDQ8NDw0PDQ8NDw0PJw8nDw0PDQ8nDycPJw8nDw0PDQ8nDycPDQ8NDw0PJw8NDw0PJw8NDw0PJw8nDw0PJw8nDw0PJw8nDw0PJw8nDw0PDQ8nDw0PDQ8NDw0PDQ8nDycPDQ8nDycPJw8NDw0PJw8NDw0PDQ8NDw0PJw8nDw0PJw8nDycPJw8nDw0PDQ8NDw0PDQ8NDw0PDQ8nDycPJw8nDycPJw8nDycPDQ8NDw0PDQ8NDw0PDQ8NDycPJw8nDycPJw8nDycPJw8NDw0PDQ8NDw0PDQ8NDw0PJw8nDycPJw8nDycPJw8nDw0PDQ8NDw0PDQ8NDw0PDQ8nDycPJw8nDycPJw8nDycPDQ8NDw0PDQ8NDw0PDQ8NDycPJw8nDycPJw8nDycPJw8nDycPJw8NDycPDQ8nDw0PDQ8NDw0PJw8NDycPDQ8nDycPDQ8NDw0PDQ8NDycPJw8NDycPJw8nDycPJw8NDw0PDQ8NDw0PDQ8NDw0PDQ8NDycPJw8nDycPJw8nDycPJw8NDw0PDQ8NDw0PDQ8NDw0PJw8nDycPJw8nDycPJw8nEgABSA==

    # RF Lights ==============================
    blank:  # 空开关
      friendly_name: Blank Switch
      command_on: ''
      command_off: ''

    light_1:
      friendly_name: Light 1
      command_on: eQAYAQgXCRYJFwgXCBcZBwgXCBcJFgoWGAcYBxkGGQcJFhgHCRcJFgkWCRYKFgkWGAcZBwjyCRYJFwgXCRYJFhkHCRYJFgkWCRcYBxkGGQcYBwkWGQcJFgkWCRcIFwkWCRYZBxgHCfEJFwkWCRYJFwgXGAcJFwgXCBcJFhkHGAcYCBgHCBcYBwkWCRcJFgkWCRcJFhgHGQcI8gkWCRYJFwgXCRYZBwgXCRcIFwgXGAcZBxgHGAcJFhkHCRYJFgkXCBcJFgkWGQcYBwnxCRcJFgkWCRcIFxkGCRcIFwkWCRYZBxgHGQcYBwkWGAcJFwkWCRYJFwgXCBcZBxgHCfEJFgkXCBcJFgkXGAcJFgkXCBcJFhgIGAcYBxgABdw=
      command_off: eQAYAQgXCRYJFwgXCBcZBwgXCBcJFgoWGAcYBxkGGQcJFhgHCRcJFgkWCRYKFgkWGAcZBwjyCRYJFwgXCRYJFhkHCRYJFgkWCRcYBxkGGQcYBwkWGQcJFgkWCRcIFwkWCRYZBxgHCfEJFwkWCRYJFwgXGAcJFwgXCBcJFhkHGAcYCBgHCBcYBwkWCRcJFgkWCRcJFhgHGQcI8gkWCRYJFwgXCRYZBwgXCRcIFwgXGAcZBxgHGAcJFhkHCRYJFgkXCBcJFgkWGQcYBwnxCRcJFgkWCRcIFxkGCRcIFwkWCRYZBxgHGQcYBwkWGAcJFwkWCRYJFwgXCBcZBxgHCfEJFgkXCBcJFgkXGAcJFgkXCBcJFhgIGAcYBxgABdw=

    # light_2:  # 旧阳台灯 停用
    #   friendly_name: Light 2
    #   command_on: egYyAAoXCRcKFwkXCRcKFwryChcKFwkXChcKFxkHCRcJFwoXChcZCBkIGQcZBwkXGQcZBxkHAAAAAAAA
    #   command_off: egYyAAoXCRcKFwkXCRcKFwryChcKFwkXChcKFxkHCRcJFwoXChcZCBkIGQcZBwkXGQcZBxkHAAAAAAAA

    light_3:
      friendly_name: Light 3
      command_on: egAQAQkWCRcIFwkWCRYZBgkXCBcJFgkWGQcYBxgHGAcJFhkGCRcIFxgHGQYJFwgXCRYJFgnxCRYJFwgXCRYJFhkGCRcIFwkWCRYZBhkHGAcYBwkWGQcIFwgXGAcZBgkXCBcJFgkWCfEJFwgWChYJFgkWGQYJFwkWCRYJFxgHGAcYBxkGCRYZBwkWCRYZBhkGCRcJFgkWCRYJ8ggXCBcJFgkWCRcYBwkWCRYJFgkXGAcYBxkGGQcIFxgHCRYJFhkHGAcIFwkWCRcJFgnxCBcJFgkXCBcJFhgHCRYKFggXCRYYBxgHGQcYBwkWGQYJFwgXGAcZBgkXCBcJFgkWCfEJFwgXCRYJFgkWGQcIFwkWCRYJAAXcAAAAAAAAAAA=
      command_off: egAQAQkWCRcIFwkWCRYZBgkXCBcJFgkWGQcYBxgHGAcJFhkGCRcIFxgHGQYJFwgXCRYJFgnxCRYJFwgXCRYJFhkGCRcIFwkWCRYZBhkHGAcYBwkWGQcIFwgXGAcZBgkXCBcJFgkWCfEJFwgWChYJFgkWGQYJFwkWCRYJFxgHGAcYBxkGCRYZBwkWCRYZBhkGCRcJFgkWCRYJ8ggXCBcJFgkWCRcYBwkWCRYJFgkXGAcYBxkGGQcIFxgHCRYJFhkHGAcIFwkWCRcJFgnxCBcJFgkXCBcJFhgHCRYKFggXCRYYBxgHGQcYBwkWGQYJFwgXGAcZBgkXCBcJFgkWCfEJFwgXCRYJFgkWGQcIFwkWCRYJAAXcAAAAAAAAAAA=

    # light_all:
    #   friendly_name: Light All
    #   command_on: egC0AAkWCRYKFQkXCRYZBgkXCBcJFggXGQYZBxgGGQcJFhkHCRYIFwkWChYYBhkHCRUJFwnxCRYKFggXCRYIGBcHChYJFggXCRYZBxgHGAcZBgoVGQcJFggXCRYJFxkGGAcJFgkWCvAJFwkWCBcJFwkWGAcIGAgWCRcJFhkHFwcZBxgHCBcYBwkWCRcJFQoWGQcYBgoWCBcJ8QkWCRYKFgkWCRYZBgoWCBcJFgkXGAYZBxkGGAAF3AAAAAA=
    #   command_off: egC0AAkWCRYKFQkXCRYZBgkXCBcJFggXGQYZBxgGGQcJFhkHCRYIFwkWChYYBhkHCRUJFwnxCRYKFggXCRYIGBcHChYJFggXCRYZBxgHGAcZBgoVGQcJFggXCRYJFxkGGAcJFgkWCvAJFwkWCBcJFwkWGAcIGAgWCRcJFhkHFwcZBxgHCBcYBwkWCRcJFQoWGQcYBgoWCBcJ8QkWCRYKFgkWCRYZBgoWCBcJFgkXGAYZBxkGGAAF3AAAAAA=

    # RF Pump ==============================
    water_pump:
      friendly_name: Pump
      command_on: sgc0AAoaChoLGhwJHAkKAAENHAgcCAoaCxoLGhwIHAgcCBwIChocCBwIHAgcCAoaHAgcCAoaCxkAAAAA
      command_off: shA0ABwIHAkKGhwIHAgcCBwIChocCRwJChoLGgsaChoKGgoaHAgLAAEPHAgcCAoaChoKGhwIHAgAAAAA

    # RF Screen ==============================
    screen:
      friendly_name: Screen
      command_on: eB0yAAgSCBIVBhUGFAYIEhUGFQYIEhUGCBMIEgnAFQYVBhQGCBIVBQgSFQYIEgkSFQYVBRUFAAAAAAAAeB0yAAgSCBIVBhUGFAYIEhUGFQYIEhUGCBMIEgnAFQYVBhQGCBIVBQgSFQYIEgkSFQYVBRUFAAAAAAAA
      command_off: eBYyABUGFQYUBggSFAYIEhUGCRIIEhUGFAYVBgkSCBIVBhUGFAYIEhUGFAYIEggSFQYIEgnAAAAAAAAAeBYyABUGFQYUBggSFAYIEhUGCRIIEhUGFAYVBgkSCBIVBhUGFAYIEhUGFAYIEggSFQYIEgnAAAAAAAAA

    screen_pause:
      friendly_name: Screen Pause
      command_on: eAwyABUGFQUVBggSFQUIExUGCBIIEhUGFQYVBggTCBIVBhUGFAYIEhUGFQYVBggSCBIIEgjAAAAAAAAA
      command_off: eAwyABUGFQUVBggSFQUIExUGCBIIEhUGFQYVBggTCBIVBhUGFAYIEhUGFQYVBggSCBIIEgjAAAAAAAAA
